os: Linux
language: c++
before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common python-software-properties -y
  - sudo apt-add-repository ppa:wpilib/toolchain -y
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update
  - sudo apt-get install frc-toolchain -y
  - sudo apt-get install default-jdk -y
  - ./gradlew assemble
script:
  - ./gradlew build
